### ISSUE TITLE
How to mount volume with umask 000?

### ISSUE THREAD

**Issue by qtopie** [katharostech/docker-plugin_seaweedfs#1]
As titled.

**Comment by zicklag** [comment]
You can add arbitrary arguments to the `weed mount` command with the `MOUNT_OPTIONS` [configuration variable](https://github.com/katharostech/docker-plugin_seaweedfs#plugin-configuration), so you should be able to do that however you would do it in seaweedfs normally. That said, it doesn't look like there are any options for that in the `weed mount` command. You would have to ask over in the SeaweedFS repository.
