### ISSUE TITLE
how to config  this plug in kubernetes cluster?

### ISSUE THREAD

**Issue by jevi061** [katharostech/docker-plugin_seaweedfs#2]
Thanks for your open source plugin.
Here I wnat to know:
What if the filer is running in container,that not use host network,
if there is a way to connect it to ?
And I Hope there is a way to specific the dest where volume sholud be placed in.
Thanks.

**Comment by zicklag** [comment]
> if there is a way to connect it to ?

If you wanted to connect to a filer that was not running in host networking mode, you would have to mount the filer port from the host into the container so that the plugin could get to the filer port inside the container by hitting the host.

> And I Hope there is a way to specific the dest where volume sholud be placed in.

You specify the place in the container that the volume should be mounted in the same way that you do with other Docker volumes. For example:

```
docker volume create --driver seaweedfs volume1
docker run -v volume1:/path/in/container mycontainer
```

**Comment by chrislusf** [comment]
FYI, maybe this a little bit related: In latest release, an "outsideContainerClusterMode" mode is added.

`weed mount -outsideContainerClusterMode`

  If the SeaweedFS system runs in a container cluster, e.g. managed by kubernetes or docker compose,
  the volume servers are not accessible by their own ip addresses.
  In "outsideContainerClusterMode", the mount will use the filer ip address instead, assuming:
    * All volume server containers are accessible through the same hostname or IP address as the filer.
    * All volume server container ports are open external to the cluster.

**Comment by zicklag** [comment]
@chrislusf That does sound applicable and, actually, even with the filer port mounted like I mentioned, it probably wouldn't work *without* that option. Unfortunately @Jevi06, I don't have time to add support for the `-outsideContainerClusterMode` option, so the only option with this plugin in its current state is probably to use host networking mode.

There is also [this](https://github.com/onaci/docker-plugin-seaweedfs) other volume plugin for SeaweedFS that you might look into if this one doesn't suite your needs, or if the developer over there has more time to implement the required features.

**Comment by jevi061** [comment]
@zicklag @chrislusf Thanks for your reply.
Here is how I use seadweedfs mount in cluster.
1.A deamonset mount filer to host path through kubernets mount propagation in every node.
2. Any pod want to use seaweedfs just mount from host path.
And after the above 2 steps done,we can do i/o opertion in pod.
Thanks for your work.
Close this issue please.

**Comment by chrislusf** [comment]
@Jevi06 I am learning Kubernetes also. 

* Could you please document the steps?
* Is it still needed to create a seaweedfs-csi-driver?

**Comment by jevi061** [comment]
> @Jevi06 I am learning Kubernetes also. 
> 
> 
> 
> * Could you please document the steps?
> 
> * Is it still needed to create a seaweedfs-csi-driver?
> 
> 

no need to create that driver,I will make a more detailed doc when I'm free.

**Comment by zicklag** [comment]
Closing this issue like @Jevi06 asked, but feel free to discuss on this thread if you want.
