### ISSUE TITLE
Volumes being created even when seaweedfs is not running

### ISSUE THREAD

**Issue by angad-k** [katharostech/docker-plugin_seaweedfs#7]
I reinstalled the plugin yesterday evening, and since then, I have been able to create volumes using this plugin even when I have not started seaweedfs server and the volumes remain visible even after stopping seaweedfs server. Also, the volumes aren't visible when I access filer through localhost:8888.

**Comment by zicklag** [comment]
Oh, that is interesting. This plugin was ported from a LizardFS plugin, and the LizardFS mount command would intentionally hang until it received a connection from the server. SeaweedFS must act differently and the command will exit whether or not it was mounted.

I don't have the time to fix it unfortunately, sorry! My organization isn't actually using this so we don't have much time to maintain it.

To fix your current setup you should be able to see the volumes in `/var/lib/docker/plugins/plugin_name/data` on your host. If you have data inside of there you need to keep you should copy it out. Then you should be able to uninstall the plugin, remove the `/var/lib/docker/plugins/plugin_name` folder if it is there, and re-install the plugin after starting the SeaweedFS server.

**Comment by angad-k** [comment]
Hey! So, I deleted the plugin and reinstalled it. I was initally tring it with the dockerized solution of seaweedfs but assumed something was wrong with the way I was deploying seaweedfs containers so I am now trying it with the seaweed binary. I started the master, volume and filer services with the `./weed server -filer=true` command and then tried making volumes with the plugin. I get logs like `I0715 23:27:21  7162 filer_grpc_server_sub_meta.go:25]  mount@192.168.0.107:41206 starts to subscribe /docker/volumes/gasper-mongodb-storage from 2020-07-15 23:27:21.607691544 +0530 IST
`. However, when I try to look at it by accessing it through localhost:8888 (filer), nothing is visible. Also, the volumes remain visible in docker even after stopping the seaweed service. So, I think nothing's actually getting uploaded to seaweedfs. Could you tell me what could be the issue? And if it's solvable by making changes to the plugin, could you point me in the right direction so I can solve it by myself?

**Comment by zicklag** [comment]
Hmm, could you try mounting the SeaweedFS fileystem somewhere manually using `weed mount` in a couple of different places to make sure that your SeaweedFS server is working fine. I'm assuming it is, but mounting it a couple different places and making sure that the volume is synchronized across the different mount points will make for sure.

---

If that *does* work, then I'll have to do a little bit of investigation and I'll let you know what I find.

**Comment by angad-k** [comment]
Hey! Sorry for the trouble. Seems that the issue was with the server. Tried mounting a directory and it gave a runtime error. I have opened an issue on the seaweedfs repo. Again, thanks for the prompt response.

**Comment by zicklag** [comment]
No problem, glad I could help!

**Comment by angad-k** [comment]
Cleared the server related problems. Wasn't much, I was just using the mount syntax a little incorrectly. Now I have tried mounting the directories to the same location and using `mkdir`, `touch` and `nano` commands in the directory and changes get reflected nicely.
However the plugin's giving the same problems as mentioned above again. Here are the server logs where I have tried mounting two volumes which are `gasper-mongodb-storage` and `gasper-redis-storage`:
<pre>
I0717 22:58:29 10845 master.go:151] current: 192.168.0.107:9333 peers:
I0717 22:58:29 10845 file_util.go:20] Folder /tmp Permission: -rwxrwxrwx
I0717 22:58:29 10845 master.go:151] current: 192.168.0.107:9333 peers:192.168.0.107:9333
I0717 22:58:29 10845 file_util.go:20] Folder /tmp Permission: -rwxrwxrwx
I0717 22:58:29 10845 master_server.go:108] Volume Size Limit is 30000 MB
I0717 22:58:29 10845 master_server.go:196] adminScripts:
I0717 22:58:29 10845 master.go:114] Start Seaweed Master 30GB 1.85 5a4f258 at 0.0.0.0:9333
I0717 22:58:29 10845 raft_server.go:47] Starting RaftServer with 192.168.0.107:9333
I0717 22:58:29 10845 raft_server.go:55] Peers Change: [] => [192.168.0.107:9333]
I0717 22:58:29 10845 volume_loading.go:104] loading index /tmp/1.idx to memory
I0717 22:58:29 10845 volume_loading.go:104] loading index /tmp/2.idx to memory
I0717 22:58:29 10845 volume_loading.go:104] loading index /tmp/4.idx to memory
I0717 22:58:29 10845 volume_loading.go:104] loading index /tmp/5.idx to memory
I0717 22:58:29 10845 volume_loading.go:104] loading index /tmp/7.idx to memory
I0717 22:58:29 10845 volume_loading.go:104] loading index /tmp/6.idx to memory
I0717 22:58:29 10845 volume_loading.go:104] loading index /tmp/3.idx to memory
I0717 22:58:29 10845 disk_location.go:87] data file /tmp/3.idx, replicaPlacement=000 v=3 size=8 ttl=
I0717 22:58:29 10845 disk_location.go:87] data file /tmp/7.idx, replicaPlacement=000 v=3 size=8 ttl=
I0717 22:58:29 10845 disk_location.go:87] data file /tmp/2.idx, replicaPlacement=000 v=3 size=8 ttl=
I0717 22:58:29 10845 disk_location.go:87] data file /tmp/5.idx, replicaPlacement=000 v=3 size=8 ttl=
I0717 22:58:29 10845 disk_location.go:87] data file /tmp/4.idx, replicaPlacement=000 v=3 size=632 ttl=
I0717 22:58:29 10845 disk_location.go:87] data file /tmp/6.idx, replicaPlacement=000 v=3 size=208 ttl=
I0717 22:58:29 10845 disk_location.go:87] data file /tmp/1.idx, replicaPlacement=000 v=3 size=112 ttl=
I0717 22:58:29 10845 disk_location.go:123] Store started on dir: /tmp with 7 volumes max 8
I0717 22:58:29 10845 disk_location.go:126] Store started on dir: /tmp with 0 ec shards
I0717 22:58:29 10845 volume_grpc_client_to_master.go:27] Volume server start with seed master nodes: [192.168.0.107:9333]
I0717 22:58:29 10845 volume.go:319] Start Seaweed volume server 30GB 1.85 5a4f258 at 0.0.0.0:8080
I0717 22:58:29 10845 volume_grpc_client_to_master.go:71] SendHeartbeat to 192.168.0.107:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.0.107:19333: connect: connection refused"
I0717 22:58:29 10845 volume_grpc_client_to_master.go:51] heartbeat error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.0.107:19333: connect: connection refused"
I0717 22:58:29 10845 raft_server.go:75] Initializing new cluster
I0717 22:58:29 10845 raft_server.go:88] current cluster leader: 192.168.0.107:9333
I0717 22:58:29 10845 master_server.go:151] [ 192.168.0.107:9333 ] I am the leader!
I0717 22:58:29 10845 master.go:138] Start Seaweed Master 30GB 1.85 5a4f258 grpc server at 0.0.0.0:19333
I0717 22:58:29 10845 master_grpc_server.go:253] + client master@192.168.0.107:40624
I0717 22:58:30 10845 master_grpc_server.go:253] + client filer@192.168.0.107:8888
I0717 22:58:30 10845 leveldb_store.go:41] filer store dir: .
I0717 22:58:30 10845 file_util.go:20] Folder . Permission: -rwxrwxr-x
I0717 22:58:30 10845 configuration.go:25] Configure filer for leveldb
I0717 22:58:30 10845 filer.go:144] Start Seaweed Filer 30GB 1.85 5a4f258 at 192.168.0.107:8888
I0717 22:58:30 10845 filer_grpc_server_sub_meta.go:130] + listener filer@192.168.0.107:33832
I0717 22:58:30 10845 filer_grpc_server_sub_meta.go:60]  filer@192.168.0.107:33832 local subscribe / from 2020-07-17 22:58:30.941924363 +0530 IST
I0717 22:58:34 10845 volume_grpc_client_to_master.go:74] Heartbeat to: 192.168.0.107:9333
I0717 22:58:34 10845 node.go:278] topo adds child DefaultDataCenter
I0717 22:58:34 10845 node.go:278] topo:DefaultDataCenter adds child DefaultRack
I0717 22:58:34 10845 node.go:278] topo:DefaultDataCenter:DefaultRack adds child 192.168.0.107:8080
I0717 22:58:34 10845 master_grpc_server.go:74] added volume server 192.168.0.107:8080
I0717 22:58:34 10845 volume_layout.go:243] Volume 7 becomes writable
I0717 22:58:34 10845 volume_layout.go:243] Volume 6 becomes writable
I0717 22:58:34 10845 volume_layout.go:243] Volume 2 becomes writable
I0717 22:58:34 10845 volume_layout.go:243] Volume 5 becomes writable
I0717 22:58:34 10845 volume_layout.go:243] Volume 4 becomes writable
I0717 22:58:34 10845 volume_layout.go:243] Volume 1 becomes writable
I0717 22:58:34 10845 volume_layout.go:243] Volume 3 becomes writable
I0717 22:58:34 10845 master_grpc_server.go:113] master see new volume 7 from 192.168.0.107:8080
I0717 22:58:34 10845 master_grpc_server.go:113] master see new volume 6 from 192.168.0.107:8080
I0717 22:58:34 10845 master_grpc_server.go:113] master see new volume 2 from 192.168.0.107:8080
I0717 22:58:34 10845 master_grpc_server.go:113] master see new volume 5 from 192.168.0.107:8080
I0717 22:58:34 10845 master_grpc_server.go:113] master see new volume 4 from 192.168.0.107:8080
I0717 22:58:34 10845 master_grpc_server.go:113] master see new volume 1 from 192.168.0.107:8080
I0717 22:58:34 10845 master_grpc_server.go:113] master see new volume 3 from 192.168.0.107:8080
I0717 22:58:34 10845 master_grpc_server.go:159] master send to master@192.168.0.107:40624: url:"192.168.0.107:8080"  public_url:"192.168.0.107:8080"  new_vids:7  new_vids:6  new_vids:2  new_vids:5  new_vids:4  new_vids:1  new_vids:3
I0717 22:58:34 10845 master_grpc_server.go:159] master send to filer@192.168.0.107:8888: url:"192.168.0.107:8080"  public_url:"192.168.0.107:8080"  new_vids:7  new_vids:6  new_vids:2  new_vids:5  new_vids:4  new_vids:1  new_vids:3
I0717 22:59:41 10845 filer_grpc_server_sub_meta.go:130] + listener mount@127.0.0.1:40778
I0717 22:59:41 10845 filer_grpc_server_sub_meta.go:25]  mount@127.0.0.1:40778 starts to subscribe / from 2020-07-17 22:09:13.919204479 +0530 IST
I0717 23:01:48 10845 filer_grpc_server_sub_meta.go:130] + listener mount@192.168.0.107:33936
I0717 23:01:48 10845 filer_grpc_server_sub_meta.go:25]  mount@192.168.0.107:33936 starts to subscribe /docker/volumes from 2020-07-17 23:01:48.601809323 +0530 IST
I0717 23:01:49 10845 filer_grpc_server_sub_meta.go:130] + listener mount@192.168.0.107:33944
I0717 23:01:49 10845 filer_grpc_server_sub_meta.go:25]  mount@192.168.0.107:33944 starts to subscribe /docker/volumes/gasper-mongodb-storage from 2020-07-17 23:01:49.140570097 +0530 IST
</pre>

Again, thanks in advance!

**Comment by chrislusf** [comment]
the logs did not show any problem. Not clear what problem you have.

**Comment by angad-k** [comment]
Yeah, the logs don't show any problem but when I look at localhost:8888, nothing seems to be uploaded. Also the volumes remain available even after I shut down the server.

**Comment by chrislusf** [comment]
* There are no logs related to "gasper-redis-storage".
  * Seems you created 3 mounts, is it expected? "/", "/docker/volumes", "/docker/volumes/gasper-mongodb-storage".

**Comment by angad-k** [comment]
I didn't create "/" and "/docker/volumes" . I created gasper-mongodb-storage and gasper-redis-storage through the plugin. I will look into why gasper-redis-storage is not being shown and send the logs again.

**Comment by angad-k** [comment]
Okay, gasper-redis-storage didn't get anything put in it and I think that's why it's not showing in the logs and yes, I initially mounted the test directories on "/" so that can be accounted for. As of "docker/volumes", I think that is related to the plugin itself. Now, what I tried was, I created a weed-vol through the plugin. There were no corresponding logs at that moment. But everytime when I run a container with weed-vol with the command `docker run -it --rm -v weed-vol:/data alpine sh`, a new log for "docker/volumes/weed-vol" appears. However localhost:8888 doesn't show anything uploaded and the volume still remains accesible after I stop the seaweed server.

**Comment by angad-k** [comment]
The logs for the above :
<pre>
I0717 23:35:51 14717 master.go:151] current: 192.168.0.107:9333 peers:
I0717 23:35:51 14717 file_util.go:20] Folder /tmp Permission: -rwxrwxrwx
I0717 23:35:51 14717 master.go:151] current: 192.168.0.107:9333 peers:192.168.0.107:9333
I0717 23:35:51 14717 file_util.go:20] Folder /tmp Permission: -rwxrwxrwx
I0717 23:35:51 14717 master_server.go:108] Volume Size Limit is 30000 MB
I0717 23:35:51 14717 master_server.go:196] adminScripts:
I0717 23:35:51 14717 master.go:114] Start Seaweed Master 30GB 1.85 5a4f258 at 0.0.0.0:9333
I0717 23:35:51 14717 raft_server.go:47] Starting RaftServer with 192.168.0.107:9333
I0717 23:35:51 14717 raft_server.go:55] Peers Change: [] => [192.168.0.107:9333]
I0717 23:35:51 14717 volume_loading.go:104] loading index /tmp/5.idx to memory
I0717 23:35:51 14717 volume_loading.go:104] loading index /tmp/2.idx to memory
I0717 23:35:51 14717 volume_loading.go:104] loading index /tmp/3.idx to memory
I0717 23:35:51 14717 volume_loading.go:104] loading index /tmp/4.idx to memory
I0717 23:35:51 14717 volume_loading.go:104] loading index /tmp/7.idx to memory
I0717 23:35:51 14717 volume_loading.go:104] loading index /tmp/6.idx to memory
I0717 23:35:51 14717 volume_loading.go:104] loading index /tmp/1.idx to memory
I0717 23:35:51 14717 disk_location.go:87] data file /tmp/1.idx, replicaPlacement=000 v=3 size=112 ttl=
I0717 23:35:51 14717 disk_location.go:87] data file /tmp/3.idx, replicaPlacement=000 v=3 size=8 ttl=
I0717 23:35:51 14717 disk_location.go:87] data file /tmp/2.idx, replicaPlacement=000 v=3 size=8 ttl=
I0717 23:35:51 14717 disk_location.go:87] data file /tmp/4.idx, replicaPlacement=000 v=3 size=632 ttl=
I0717 23:35:51 14717 disk_location.go:87] data file /tmp/6.idx, replicaPlacement=000 v=3 size=208 ttl=
I0717 23:35:51 14717 disk_location.go:87] data file /tmp/7.idx, replicaPlacement=000 v=3 size=8 ttl=
I0717 23:35:51 14717 disk_location.go:87] data file /tmp/5.idx, replicaPlacement=000 v=3 size=8 ttl=
I0717 23:35:51 14717 disk_location.go:123] Store started on dir: /tmp with 7 volumes max 8
I0717 23:35:51 14717 disk_location.go:126] Store started on dir: /tmp with 0 ec shards
I0717 23:35:51 14717 volume.go:319] Start Seaweed volume server 30GB 1.85 5a4f258 at 0.0.0.0:8080
I0717 23:35:51 14717 volume_grpc_client_to_master.go:27] Volume server start with seed master nodes: [192.168.0.107:9333]
I0717 23:35:51 14717 volume_grpc_client_to_master.go:71] SendHeartbeat to 192.168.0.107:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.0.107:19333: connect: connection refused"
I0717 23:35:51 14717 volume_grpc_client_to_master.go:51] heartbeat error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.0.107:19333: connect: connection refused"
I0717 23:35:51 14717 raft_server.go:75] Initializing new cluster
I0717 23:35:51 14717 raft_server.go:88] current cluster leader: 192.168.0.107:9333
I0717 23:35:51 14717 master_server.go:151] [ 192.168.0.107:9333 ] I am the leader!
I0717 23:35:51 14717 master.go:138] Start Seaweed Master 30GB 1.85 5a4f258 grpc server at 0.0.0.0:19333
I0717 23:35:51 14717 master_grpc_server.go:253] + client master@192.168.0.107:41058
I0717 23:35:52 14717 master_grpc_server.go:253] + client filer@192.168.0.107:8888
I0717 23:35:52 14717 leveldb_store.go:41] filer store dir: .
I0717 23:35:52 14717 file_util.go:20] Folder . Permission: -rwxrwxr-x
I0717 23:35:53 14717 configuration.go:25] Configure filer for leveldb
I0717 23:35:53 14717 filer.go:144] Start Seaweed Filer 30GB 1.85 5a4f258 at 192.168.0.107:8888
I0717 23:35:53 14717 filer_grpc_server_sub_meta.go:130] + listener filer@192.168.0.107:34266
I0717 23:35:53 14717 filer_grpc_server_sub_meta.go:60]  filer@192.168.0.107:34266 local subscribe / from 2020-07-17 23:35:53.001476766 +0530 IST
I0717 23:35:56 14717 volume_grpc_client_to_master.go:74] Heartbeat to: 192.168.0.107:9333
I0717 23:35:56 14717 node.go:278] topo adds child DefaultDataCenter
I0717 23:35:56 14717 node.go:278] topo:DefaultDataCenter adds child DefaultRack
I0717 23:35:56 14717 node.go:278] topo:DefaultDataCenter:DefaultRack adds child 192.168.0.107:8080
I0717 23:35:56 14717 master_grpc_server.go:74] added volume server 192.168.0.107:8080
I0717 23:35:56 14717 volume_layout.go:243] Volume 2 becomes writable
I0717 23:35:56 14717 volume_layout.go:243] Volume 1 becomes writable
I0717 23:35:56 14717 volume_layout.go:243] Volume 3 becomes writable
I0717 23:35:56 14717 volume_layout.go:243] Volume 7 becomes writable
I0717 23:35:56 14717 volume_layout.go:243] Volume 6 becomes writable
I0717 23:35:56 14717 volume_layout.go:243] Volume 5 becomes writable
I0717 23:35:56 14717 volume_layout.go:243] Volume 4 becomes writable
I0717 23:35:56 14717 master_grpc_server.go:113] master see new volume 2 from 192.168.0.107:8080
I0717 23:35:56 14717 master_grpc_server.go:113] master see new volume 1 from 192.168.0.107:8080
I0717 23:35:56 14717 master_grpc_server.go:113] master see new volume 3 from 192.168.0.107:8080
I0717 23:35:56 14717 master_grpc_server.go:113] master see new volume 7 from 192.168.0.107:8080
I0717 23:35:56 14717 master_grpc_server.go:113] master see new volume 6 from 192.168.0.107:8080
I0717 23:35:56 14717 master_grpc_server.go:113] master see new volume 5 from 192.168.0.107:8080
I0717 23:35:56 14717 master_grpc_server.go:113] master see new volume 4 from 192.168.0.107:8080
I0717 23:35:56 14717 master_grpc_server.go:159] master send to master@192.168.0.107:41058: url:"192.168.0.107:8080"  public_url:"192.168.0.107:8080"  new_vids:2  new_vids:1  new_vids:3  new_vids:7  new_vids:6  new_vids:5  new_vids:4
I0717 23:35:56 14717 master_grpc_server.go:159] master send to filer@192.168.0.107:8888: url:"192.168.0.107:8080"  public_url:"192.168.0.107:8080"  new_vids:2  new_vids:1  new_vids:3  new_vids:7  new_vids:6  new_vids:5  new_vids:4
I0717 23:38:03 14717 filer_grpc_server_sub_meta.go:130] + listener mount@192.168.0.107:34400
I0717 23:38:03 14717 filer_grpc_server_sub_meta.go:25]  mount@192.168.0.107:34400 starts to subscribe /docker/volumes/weed-vol from 2020-07-17 23:38:03.915681255 +0530 IST
I0717 23:43:23 14717 filer_grpc_server_sub_meta.go:130] + listener mount@192.168.0.107:34432
I0717 23:43:23 14717 filer_grpc_server_sub_meta.go:25]  mount@192.168.0.107:34432 starts to subscribe /docker/volumes/weed-vol from 2020-07-17 23:43:23.130224926 +0530 IST
I0717 23:43:47 14717 filer_grpc_server_sub_meta.go:130] + listener mount@192.168.0.107:34440
I0717 23:43:47 14717 filer_grpc_server_sub_meta.go:25]  mount@192.168.0.107:34440 starts to subscribe /docker/volumes/weed-vol from 2020-07-17 23:43:47.821365309 +0530 IST
I0717 23:46:10 14717 filer_grpc_server_sub_meta.go:130] + listener mount@192.168.0.107:34454
I0717 23:46:10 14717 filer_grpc_server_sub_meta.go:25]  mount@192.168.0.107:34454 starts to subscribe /docker/volumes/weed-vol from 2020-07-17 23:46:10.533005347 +0530 IST
^Cvolume server has be killed
I0717 23:47:25 14717 volume.go:245] graceful stop cluster http server, elapsed [0]
I0717 23:47:25 14717 volume.go:250] graceful stop gRPC, elapsed [0]
I0717 23:47:25 14717 volume_server.go:103] Shutting down volume server...
I0717 23:47:25 14717 volume_server.go:105] Shut down successfully!
I0717 23:47:25 14717 volume.go:255] stop volume server, elapsed [0]
W0717 23:47:25 14717 volume.go:265] the volume server exit.
</pre>

As you can see, the weed-vol log appears four times for the four times I ran the `docker run -it --rm -v weed-vol:/data alpine sh` command.

**Comment by chrislusf** [comment]
Sorry, I do not understand what is in " I created a weed-vol through the plugin", what is working, what is not.

**Comment by angad-k** [comment]
Sorry for the ambiguity. I mean I created a volume through this plugin with the name "weed-vol". What's not working is if something's being uploaded, which should be the case as I did `cp -R /etc .` in the container started with `docker run -it --rm -v weed-vol:/data alpine sh`, the stuff that's getting uploaded should also be visible on localhost:8888. However, in this case, nothing is visible on localhost:8888

**Comment by zicklag** [comment]
I don't have time right now to look into it, so my only advice would be to shut the server down, remove the plugin, and re-install the plugin, maybe with a different alias just in case, and then try to follow the instructions on the README to the letter and see if you can get that to work.

That might not be necessary, though, and I'll try to do a deeper check when I get the chance.

**Comment by chrislusf** [comment]
* Use some screenshots. What you described may be different.
* Try to start mount with verbose logs, `weed -v=4 mount` and see the logs.

**Comment by nivekuil** [comment]
Took me way too long but I figured it out: `apk install fuse3` does not provide `fusermount`, which `weed mount` seems to require, but `fusermount3`.

Fun story, the reason it took me so long is because this plugin actually logged `weed` output in binary so I had to piece it together from this (0a0a added by me):
```
0a 45 78 61 6d 70 6c 65 3a 20 77 65 65 64 20 6d 6f 75 6e 74 20 2d 66 69 6c 65 72 3d 6c 6f 63 61 6c 68 6f 73 74 3a 38 38 38 38 20 2d 64 69 72 3d 2f 73
0a0a

66 6c 61 67 20 70 72 6f 76 69 64 65 64 20 62 75 74 20 6e 6f 74 20 64 65 66 69 6e 65 64 3a 20 2d 64 69 72 41 75 74 6f 43 72 65 61 74 65 0a 45 78 61 6d 

78 61 6d 70 6c 65 3a 20 77 65 65 64 20 6d 6f 75 6e 74 20 2d 66 69 6c 65 72 3d 6c 6f 63 61 6c 68 6f 73 74 3a 38 38 38 38 20 2d 64 69 72 3d 2f 73 6f

0a0a

54 68 69 73 20 69 73 20 53 65 61 77 65 65 64 46 53 20 76 65 72 73 69 6f 6e 20 33 30 47 42 20 32 2e 31 34 20 34 36 62 39 31 32 32 20 6c 69 6e 75 78 20

0a0a

49 31 32 31 30 20 30 31 3a 31 37 3a 33 35 20 20 20 20 32 39 20 6c 65 76 65 6c 64 62 5f 73 74 6f 72 65 2e 67 6f 3a 34 30 5d 20 66 69 6c 65 72 20 73 74

0a0a
49 31 32 31 30 20 30 31 3a 31 37 3a 33 35 20 20 20 20 32 39 20 66 69 6c 65 5f 75 74 69 6c 2e 67 6f 3a 32 33 5d 20 46 6f 6c 64 65 72 20 2f 74 6d 70 2f


```
Unfortunately the docker logs truncated binary by default so I had to add `.toString` to the error checks, then I got this: 
```
level=info msg="[INFO]:  This is SeaweedFS version 30GB 2.14 46b9122 linux amd64" plugin=19c2c4521509041fb6b7a65331d6a39d5a8fe844b5dba6b70df71af62ee1f53c
level=info msg="mount point owner uid=0 gid=0 mode=drwxr-xr-x" plugin=19c2c4521509041fb6b7a65331d6a39d5a8fe844b5dba6b70df71af62ee1f53c
level=info msg="current uid=0 gid=0" plugin=19c2c4521509041fb6b7a65331d6a39d5a8fe844b5dba6b70df71af62ee1f53c
level=info plugin=19c2c4521509041fb6b7a65331d6a39d5a8fe844b5dba6b70df71af62ee1f53c
level=error msg="[ERROR]:  I1210 01:42:39    44 leveldb_store.go:40] filer store dir: /tmp/4394/meta" plugin=19c2c4521509041fb6b7a65331d6a39d5a8fe844b5dba6b70df71af62ee1f53c
level=error msg="I1210 01:42:39    44 file_util.go:23] Folder /tmp/4394/meta Permission: -rwxr-xr-x" plugin=19c2c4521509041fb6b7a65331d6a39d5a8fe844b5dba6b70df71af62ee1f53c
level=error plugin=19c2c4521509041fb6b7a65331d6a39d5a8fe844b5dba6b70df71af62ee1f53c
level=error msg="[ERROR]:  I1210 01:42:39    44 mount_std.go:197] mount: fusermount: exec: \"fusermount\": executable file not found in $PATH" plugin=19c2c4521509041fb6b7a65331d6a39d5a8fe844b5dba6b70>
```

I'll put up a PR.

**Comment by zicklag** [comment]
Woah, binary logging! My bad. That is awful LOL. Good find and thanks for the PR. :+1:
